export const IDENTITY_FROM_PERMISSIONS = 'identityFromPermissions'
export const REQUEST_TRANSFER = 'requestTransfer'
export const CALLCONTRACTFUNCTION = 'callContractFunction'
export const GETACCOUNTINFO = 'getAccountInfo'
export const TRANSFER_NH_ASSET = 'transferNHAsset'
export const CREATE_NH_ASSET_ORDER = 'creatNHAssetOrder'
export const FILL_NH_ASSET_ORDER = 'fillNHAssetOrder'
export const CANCEL_NH_ASSET_ORDER = 'cancelNHAssetOrder'